---
format: 
  html:
    include-in-header: 
      - includes/icons.html
page-layout: full
---

## [Research]{style="color: #1E354B"}

#### [Area of Focus]{style="color: #7f7f7f"}

My lab is focused on studying adverse cardiovascular effects of common chronic diseases (hypertension, type 2 diabetes, thromboembolic disorders) and optimizing drug therapy to minimize risks of these diseases.

A major focus is on adverse effects of chronic **uncontrolled blood pressure (hypertension)** and ways to optimize antihypertensive drug therapy to mitigate these adverse effects. I have particular expertise in the area of **treatment-resistant hypertension**.

#### [Methods]{style="color: #7f7f7f"}

My research spans population and clinical sciences related to cardiovascular disease and its treatment. This includes both observational research, as well as clinical trial work, primarily through my collaboration with colleagues in the [Division of Cardiovascular Medicine](https://cardiology.medicine.ufl.edu/).

I am also interested in research on methods for using electronic health record (EHR) data, including how to minimize misclassification when measuring longitudinal drug exposure from EHR prescribing data, and methods for dealing with missingness in EHR data and biases associated with missing data.

#### [Current Projects & Funding]{style="color: #7f7f7f"}

Current projects and funding for my lab can be found at the [CVmedLab website](https://cvmedlab.org/).

#### [Publications]{style="color: #7f7f7f"}

A complete list of my lab's journal publications can be found on [PubMed](https://www.ncbi.nlm.nih.gov/myncbi/steven.smith.4/bibliography/public/) or [Google Scholar](https://scholar.google.com/citations?user=3MKlN-EAAAAJ&hl=en). Newer publications are also available via [ORCID](https://orcid.org/0000-0002-0201-839X). If you do not have access to a particular journal, please [email me](mailto:ssmith@cop.ufl.edu) for an author's print.
